FROM ruby:3.3.3-slim

# 必要なパッケージをインストール
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    npm \
    git \
    vim \
    curl \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# yarnのインストール
RUN npm install -g yarn

# 作業ディレクトリを設定
WORKDIR /app

# Gemfileがあればコピー
COPY Gemfile* ./

# bundlerを最新版にアップデート
RUN gem install bundler

# ポート3000を公開
EXPOSE 3000

# entrypointスクリプトをコピー
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

# デフォルトコマンド
CMD ["rails", "server", "-b", "0.0.0.0"]