services:
  db:
    image: postgres:15-alpine
    container_name: kudos_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tmp/postgres_backup:/backup
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kudos_development
      TZ: Asia/Tokyo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kudos_web
    command: ["rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      RAILS_ENV: development
      TZ: Asia/Tokyo
    restart: unless-stopped

  # TailwindCSS監視用（後で追加）
  # css:
  #   build: .
  #   container_name: kudos_css
  #   command: bash -c "bin/rails tailwindcss:watch"
  #   volumes:
  #     - .:/app
  #     - bundle_data:/usr/local/bundle
  #     - node_modules:/app/node_modules
  #   depends_on:
  #     - web
  #   environment:
  #     RAILS_ENV: development

volumes:
  postgres_data:
  bundle_data:
  node_modules: